# Generated by Django 6.1 on 2026-08-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asthamarket', '0003_signup'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Signup',
        ),
    ]
